class CFB_ThingReplacer : StaticEventHandler
{
    override void CheckReplacement(ReplaceEvent e)
    {
        CVar spawnAltWeapons = CVar.FindCVar('sv_cfb_spawnaltweapons');
		// check if the class exists first
		let cls = e.Replacee.GetClassName(); //Although not necessary, it helps out for simplification.
		switch(cls)
		{
		//==== Weapon replacements ====//
		// Vanilla & Legacy of Rust
			case 'Chaingun':
				if (spawnAltWeapons.GetBool())
				{
					if (random(0, 1) == 0)
						e.Replacement = "CFB_Chaingun";
					else
						e.Replacement = "CFB_HeavyCannon";
				}
				else
					e.Replacement = "CFB_Chaingun";
				break;
			case 'RocketLauncher':
				if (spawnAltWeapons.GetBool())
				{
					if (random(0, 1) == 0)
						e.Replacement = "CFB_RocketLauncher";
					else
						e.Replacement = "CFB_GrenadeLauncher";
				}
				else
					e.Replacement = "CFB_RocketLauncher";
				break;
			case 'PlasmaRifle':
				if (spawnAltWeapons.GetBool())
				{
					if (random(0, 1) == 0)
						e.Replacement = "CFB_PlasmaRifle";
					else
						e.Replacement = "CFB_Flasher";
				}
				else
				{
				// this is dumb but it seems to work????
					if (StringTable.Localize(Inventory(GetDefaultByType(e.Replacee)).pickupMsg) == "You got the incinerator!")
						e.Replacement = "CFB_Flasher";
					else
						e.Replacement = "CFB_PlasmaRifle";
				}
				break;
			case 'ID24Incinerator':
				if (spawnAltWeapons.GetBool())
				{
					if (random(0, 1) == 0)
						e.Replacement = "CFB_Flasher";
					else
						e.Replacement = "CFB_PlasmaRifle";
				}
				else
					e.Replacement = "CFB_Flasher";
				break;
			case 'ID24CalamityBlade':
				e.Replacement = "CFB_CalamityArrow";
				break;
		// Eviternity I & II
			case 'Perforator': // I dunno, man. I GUESS??????
				e.Replacement = "CFB_HeavyCannon";
				break;
		// Paradise, Godless Night, and any other map(set) that uses Supercharge
			case 'TangoChainsaw':
				e.Replacement = "CFB_Chainsaw";
				break;
			case 'TangoPistol':
				e.Replacement = "CFB_Pistol";
				break;
			case 'TangoShotgun':
				e.Replacement = "CFB_PumpShotgun";
				break;
			case 'TangoSuperShotgun':
				e.Replacement = "CFB_OUShotgun";
				break;
			case 'TangoChaingun':
			case 'TangoAssaultRifle':
				e.Replacement = "CFB_Chaingun"; // ...Maybe?
				break;
			case 'TangoMinigun':
				e.Replacement = "CFB_HeavyCannon"; // Since both are here, and the Minigun is kind of a reward for beating that one part of The Old Earth...
				break;
			case 'TangoRocketLauncher':
				if (spawnAltWeapons.GetBool())
				{
					if (random(0, 1) == 0)
						e.Replacement = "CFB_RocketLauncher";
					else
						e.Replacement = "CFB_GrenadeLauncher";
				}
				else
					e.Replacement = "CFB_RocketLauncher";
				break;
			case 'TangoPlasmaRifle':
				if (spawnAltWeapons.GetBool())
				{
					if (random(0, 1) == 0)
						e.Replacement = "CFB_PlasmaRifle";
					else
						e.Replacement = "CFB_Flasher";
				}
				else
					e.Replacement = "CFB_PlasmaRifle";
				break;
			case 'TangoBFG9000':
				e.Replacement = "CFB_CalamityArrow";
				break;
//			case 'TangoStomper':
//				e.Replacement = "";
//				break;
//			case 'TangoScrapgun':
//				e.Replacement = "";
//				break;
			// Nailgun seems to be unused and inaccessible
		// Skulltag
			case 'ChaingunSpawner':
				if (random(0, 1) == 0)
					e.Replacement = "CFB_Chaingun";
				else
					e.Replacement = "CFB_HeavyCannon";
				break;
			case 'Minigun':
			case 'PTag_Minigun':
				if (spawnAltWeapons.GetBool())
				{
					if (random(0, 1) == 0)
						e.Replacement = "CFB_HeavyCannon";
					else
						e.Replacement = "CFB_Chaingun";
				}
				else
					e.Replacement = "CFB_HeavyCannon";
				break;
			case 'RocketLauncherSpawner':
				if (random(0, 1) == 0)
					e.Replacement = "CFB_RocketLauncher";
				else
					e.Replacement = "CFB_GrenadeLauncher";
				break;
			case 'GrenadeLauncher':
			case 'PTag_GrenadeLauncher':
				if (spawnAltWeapons.GetBool())
				{
					if (random(0, 1) == 0)
						e.Replacement = "CFB_GrenadeLauncher";
					else
						e.Replacement = "CFB_RocketLauncher";
				}
				else
					e.Replacement = "CFB_GrenadeLauncher";
				break;
			case 'PlasmaRifleSpawner':
				if (random(0, 1) == 0)
					e.Replacement = "CFB_PlasmaRifle";
				else
					e.Replacement = "CFB_Flasher";
				break;
			case 'Railgun':
			case 'PTag_Railgun':
				if (spawnAltWeapons.GetBool())
				{
					if (random(0, 1) == 0)
						e.Replacement = "CFB_Flasher";
					else
						e.Replacement = "CFB_PlasmaRifle";
				}
				else
					e.Replacement = "CFB_Flasher";
				break;
			case 'BFGSpawner':
			case 'BFG10K':
			case 'PTag_BFG10K':
				e.Replacement = "CFB_CalamityArrow";
				break;
		//==== Ammo replacements ====//
		// Paradise, Godless Night, and any other map(set) that uses Supercharge
			case 'TangoBulletClip':
			case 'TangoBulletClipHalf':
				e.Replacement = "CFB_Magazine";
				break;
			case 'TangoBulletBox':
				e.Replacement = "CFB_MagazineBox";
				break;
			case 'TangoShell':
				e.Replacement = "CFB_Shells";
				break;
			case 'TangoShellBox':
				e.Replacement = "CFB_ShellBox";
				break;
			case 'TangoRocketAmmo':
				e.Replacement = "CFB_RocketAmmo";
				break;
			case 'TangoRocketBox':
				e.Replacement = "CFB_RocketBox";
				break;
			case 'TangoCell':
				e.Replacement = "CFB_Cell";
				break;
			case 'TangoCellPack':
				e.Replacement = "CFB_CellPack";
				break;
//			case 'TangoScrapDrum':
//				e.Replacement = "";
//				break;
//			case 'TangoScrapDrumPack':
//				e.Replacement = "";
//				break;
//			case 'TangoStomperAmmo':
//				e.Replacement = "";
//				break;
//			case 'TangoStomperBox':
//				e.Replacement = "";
//				break;
			// Nailgun seems to be unused and inaccessible
		//==== Item replacements ====//
		// Paradise, Godless Night, and any other map(set) that uses Supercharge
			case 'TangoBerserk':
				e.Replacement = "CFB_Berserk";
				break;
//			case 'TangoVioletArmorSmall':
//				e.Replacement = "";
//				break;
//			case 'TangoVioletArmorMedium':
//				e.Replacement = "";
//				break;
//			case 'TangoVioletArmorLarge':
//				e.Replacement = "";
//				break;
//			case 'TangoArmorBonus':
//				e.Replacement = "";
//				break;
//			case 'TangoGreenArmor':
//				e.Replacement = "";
//				break;
//			case 'TangoBlueArmor':
//				e.Replacement = "";
//				break;
//			case 'TangoStimpack':
//				e.Replacement = "";
//				break;
//			case 'TangoMedkit':
//				e.Replacement = "";
//				break;
		// Skulltag
//			case 'BlueArmorSpawner':
//				e.Replacement = "";
//				break;
//			case 'ArmorBonus2':
//				e.Replacement = "";
//				break;
//			case 'HealthBonus2':
//				e.Replacement = "";
//				break;
//			case 'RedArmor':
//				e.Replacement = "";
//				break;
		}
    }
}