class CFB_Magazine : Ammo replaces Clip
{
	Default
	{
		Inventory.PickupMessage "$GOTMAGAZINE";
		Inventory.Amount 10;
		Inventory.MaxAmount 200;
		Ammo.BackpackAmount 10;
		Ammo.BackpackMaxAmount 400;
		Inventory.Icon "AMAGA0";
		Tag "$AMMO_MAGAZINE";
	}
	States
	{
		Spawn:
			AMAG A -1;
			Stop;
	}
}
class CFB_MagazineBox : CFB_Magazine replaces ClipBox
{
	Default
	{
		Inventory.PickupMessage "$GOTMAGAZINEBOX";
		Inventory.Amount 50; // 5x
		Tag "$AMMO_MAGAZINEBOX";
	}
	States
	{
		Spawn:
			AMAG B -1;
			Stop;
	}
}

class CFB_Shells : Ammo replaces Shell
{
	Default
	{
		Inventory.PickupMessage "$GOTCFBSHELLS";
		Inventory.Amount 4;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 4;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "ASHLA0";
		Tag "$AMMO_SHELLS";
	}
	States
	{
		Spawn:
			ASHL A -1;
			Stop;
	}
}
class CFB_ShellBox : CFB_Shells replaces ShellBox
{
	Default
	{
		Inventory.PickupMessage "$GOTCFBSHELLBOX";
		Inventory.Amount 20; // 5x
		Tag "$AMMO_SHELLBOX";
	}
	States
	{
		Spawn:
			ASHL B -1;
			Stop;
	}
}

class CFB_RocketAmmo : Ammo replaces RocketAmmo
{
	Default
	{
		Inventory.PickupMessage "$GOTCFBROCKET";
		Inventory.Amount 1;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "AROCA0";
		Tag "$AMMO_ROCKET";
	}
	States
	{
		Spawn:
			AROC A -1;
			Stop;
	}
}
class CFB_RocketBox : CFB_RocketAmmo replaces RocketBox
{
	Default
	{
		Inventory.PickupMessage "$GOTCFBROCKETBOX";
		Inventory.Amount 5; // 5x
		Tag "$AMMO_ROCKETBOX";
	}
	States
	{
		Spawn:
			AROC B -1;
			Stop;
	}
}

class CFB_Cell : Ammo replaces Cell
{
	Default
	{
		Inventory.PickupMessage "$GOTCFBCELL";
		Inventory.Amount 20;
		Inventory.MaxAmount 300;
		Ammo.BackpackAmount 20;
		Ammo.BackpackMaxAmount 600;
		Inventory.Icon "ACELA0";
		Tag "$AMMO_CELL";
	}
	States
	{
		Spawn:
			ACEL A -1;
			Stop;
	}
}
class CFB_CellPack : CFB_Cell replaces CellPack
{
	Default
	{
		Inventory.PickupMessage "$GOTCFBCELLPACK";
		Inventory.Amount 100; // 5x
		Tag "$AMMO_CELLPACK";
	}
	States
	{
		Spawn:
			ACEL B -1;
			Stop;
	}
}