class CFB_Berserk : Berserk replaces Berserk // Cheers, Tango, for like, the fifteenth time.
{
	Default
	{
		Inventory.PickupMessage "$GOTCFBBERSERK";
	}
	States
	{
		Spawn:
			PZRK A -1;
			Stop;
		Pickup:
			TNT1 A 0 {
				A_GiveInventory("CFB_PowerStrength");
				HealThing(100, 0);
				A_SetBlend("Red", .25, 35); // from Supercharge
			}
			Stop;
	}
}
class CFB_PowerStrength : PowerStrength replaces PowerStrength
{
	Default
	{
		Powerup.Duration 1;
		Powerup.Color "000000", 0.0;
		+INVENTORY.HUBPOWER
	}
}