class CFB_Chainsaw : CFB_Weapon replaces Chainsaw
{
	Default
	{
		+WEAPON.MELEEWEAPON
		+WEAPON.NOAUTOSWITCHTO
		Weapon.SlotNumber 1;
		Weapon.SelectionOrder 2200;
		Weapon.Kickback 0;

		Tag "$TAG_CHAINSAW";
		Obituary "$KILLCHAINSAW";
		Inventory.PickupMessage "$GOTCHAINSAW";

		Weapon.UpSound "weapons/sawup";
		Weapon.ReadySound "weapons/sawidle";
	}
	States
	{
		Spawn:
			CSAW A -1;
			Stop;
		Select:
			SAWG C 1 A_Raise(18);
			Loop;
		Deselect:
			SAWG C 1 A_Lower(18);
			Loop;
		Ready:
			SAWG CD 4 A_WeaponReady;
			Loop;
		Fire:
			SAWG AB 4 A_Saw(damage: 9, flags: SF_NORANDOM);
			SAWG B 0 A_ReFire;
			Goto Ready;
	}
}